Lesson 9
gnomePasaran/blog-platform-on-react pull request #11
Opened 2017-04-17 18:25 UTC by gnomePasaran

2017-04-21 04:59 UTC, index01d requested changes

2017-04-21 04:59 UTC, index01d commented on src/routes/Blog.js
> +    store.dispatch(fetchPost(params.id));
Нужно обязательно накинуть Promise.all и вернуть Promise.all от двух запросов, иначе если fetchPost ответит позже fetchComments, то серверный рендеринг не дождется и отдаст страничку без поста.

2017-04-21 05:00 UTC, index01d commented
CommentsContainer разместить довольно просто: ты в любой точке приложения можешь импортировать его и отобразить его элемент (e.g.: `<CommentsContainer postId={post.id}  />`)

2017-04-21 05:01 UTC, index01d commented
по вопросу с ошибкой: я максимум завтра утром склонирую проект и посмотрю что там.

2017-04-24 10:19 UTC, index01d commented
Ошибка возникает в EditPostContainer (о чем кстати по сути написано в Chrome Dev консоли). 27 строка, пост еще не загрузился и в поле entry null. Тем не менее от null пытаются взять поле title, которого там нет.

2017-04-24 10:19 UTC, index01d commented
Давай еще вычистим лишние файлы из корня проекта и нужно немного поработать над аккуратностью интерфейса:)

2017-04-24 16:25 UTC, gnomePasaran commented
да, я как бы знал, в чём ошибка, что от null берётся поле, отсюда ошибка. Я не до конца уверен, как верно её разрешить. Не обнулять в редьюсере entry?

Да, интерфейс корявенький, я на него забил, т.к. тяжело заботится об интерфейсе, когда не понимаешь как реализовать функционал. Но на 9-м уроке я раобрался с пониманием процесса. Так что время заняться им! ;)

2017-04-24 16:43 UTC, index01d commented
просто использовать get(state, 'entry.title', '') (где get - функция из lodash/object)

2017-04-25 20:24 UTC, gnomePasaran commented
https://github.com/gnomePasaran/blog-platform-on-react/pull/11/commits/ec01b8122f59a590a63f1bebd2cf34b7e6d763be
вот, добавил, ошибки не возникает. Но по прежнему не могу понять, почему initialValues всё равно пусты, хотя редьюсор отрабатывает правильно и возвращает посты. Никак не пойму, как сделать, чтобы по клику на кнопу Edit Post в поля ввода подгружались данные?  Но, когда я перехожу на страницу `http://localhost:3000/post/1/edit` и жму `F5` данные нормально подгружаются. В чём я ошибся, где корень моего не понимания работы редакс, не пойму?

2017-04-25 20:38 UTC, gnomePasaran commented
Было замечание 

> Нужно обязательно накинуть Promise.all и вернуть Promise.all от двух запросов, иначе если fetchPost ответит позже fetchComments, то серверный рендеринг не дождется и отдаст страничку без поста.

это максимум до чего я додумался, ошибки не возникает, но при обновлении страницы через F5 пост не подгружается, скорее всего ты имел в виду, что-то более уместное чем это:

```
const PostRoutes = {
  path: postPath(),
  component: PostContainer,
  prepareData: (store, query, params) => {
    if (initialLoad()) return;

    Promise.all([
      store.dispatch(fetchPost(params.id)),
      store.dispatch(fetchComments(params.id))
    ]);
  }
};
```

2017-04-25 20:40 UTC, gnomePasaran commented
И да, я немного подправил интерфейс :))

2017-04-27 07:07 UTC, index01d commented
> это максимум до чего я додумался, ошибки не возникает, но при обновлении страницы через F5 пост не подгружается, скорее всего ты имел в виду, что-то более уместное чем это:

Все правильно, но этот promise функция prepareData должна вернуть. То есть добавь return. Иначе в render.js никто не дожидается выполнения этого promis'a

2017-04-27 07:09 UTC, index01d commented on src/containers/EditPostContainer.js
> +  form: 'editPost',
добавь сюда `enableReinitialize: true`, вероятно это решит проблему с полями

2017-04-28 07:21 UTC, index01d commented
уже смотреть, или еще не смотреть?:))

2017-04-28 07:33 UTC, gnomePasaran commented
Да)) думаю можно смотреть)) 
Огромное спасибо за ревью и советы! :)

в крайнем коммите, перебросил представления Search из BlogPage в Pagination, думаю тут же нет ничего криминального?)))
И небольшой вопрос, это нормално https://github.com/gnomePasaran/blog-platform-on-react/pull/11/files#diff-28f77cd6c88a203ab1bedbd1f3e4d8f9 чтобы в презентационном компоненте была функция map, которая в цикле что-то там рендерит? Или в предь нужно переносить такое в редакс-компонент?
Ещё раз спасибо за своевременные и точные ответы))

2017-04-28 07:36 UTC, index01d commented
> И небольшой вопрос, это нормално https://github.com/gnomePasaran/blog-platform-on-react/pull/11/files#diff-28f77cd6c88a203ab1bedbd1f3e4d8f9 чтобы в презентационном компоненте была функция map, которая в цикле что-то там рендерит?

Абсолютная норма и никак по-другому нельзя.

> в крайнем коммите, перебросил представление Search из BlogPage в Pagination, думаю тут же нет ничего криминального?)))

Несколько позднее гляну, но звучит не слишком хорошо:)

2017-05-09 05:02 UTC, index01d approved these changes

2017-05-13 14:52 UTC, merged