Lesson 5
gnomePasaran/blog-platform-on-react pull request #5
Opened 2017-01-31 21:30 UTC by gnomePasaran

Эдуард, доброго времени суток))
я сделал и задание и доп., сделал как смог, пытался декомпозировать компоненты, не совмещать презинтационные компоненты, и т.д.
Больших трудностей задание не вызвало, с отображением одного поста я разобрался почти сразу(спасибо Chrome dev tools), но проблема возникла кликом по кнопке Like. Как я не пытался её решить, всё что смог - вернуться к первоначальному варианту, когда обработчик кликов был в компоненте Like. А вторая основная проблема, это сама архитектура и иерархия компонентов.
И конечно, хотелось бы узнать, приемлимо ли то, или иное моё решение, и как вместо него нужно было сделать кошерно и правильно.)

Не смотря на то, что это работает, мне кажется, что самые упоротые индусы позавидовали бы моему говнокоду )))

P.S. За ранее спасибо))

2017-02-01 10:12 UTC, index01d requested changes
Предлагаю удалить из корня все остатки предыдущих уроков. Также предлагаю создать директории components/containers и components/views

В контейнеры соответственно всю контейнерную логику, в представления все верхние компоненты основных страниц

Еще нужно определиться либо все JSX, либо все non-JSX, но не вперемешку

2017-02-01 10:12 UTC, index01d commented on src/components/BlogPage.js
>  class BlogPage extends React.Component {
Нужно выделить отсюда PaginationContainer и унести в него всё, что связано с пейджинацией

2017-02-01 10:12 UTC, index01d commented on src/components/BlogPage.js
> +        <Grid columns={2}>
Презентационная логика в контейнерном компоненте, нужно создать BlogPageView и вынести это все туда.

2017-02-01 10:12 UTC, index01d commented on src/components/BlogPage.js
> +    const likesChartData = _.map(blogs, (blog) => (
Можно выделить в PieChartContainer

2017-02-01 10:12 UTC, index01d commented on src/components/layouts/MainLayout.js
> +    { props.location.pathname != '/' && <GoBackButton />}
Layout - презентационный компонент, он не должен знать о состоянии браузера. Можно выделить расчет этого свойства в MainLayoutContainer

2017-02-01 10:12 UTC, index01d commented on src/components/layouts/MainLayout.js
> +      <Link to='/'>Tinknetica Blog</Link>
Thinknetica ;)

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/BlogItem.js
>      React.createElement(Image, assign({}, props.blog.img)),
чута везде JSX, а тут не jsx, непорядок, надо определиться

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/SearchForm.js
> +import _ from 'lodash';
Импортировать нужно конкретные функции
e.g.:
import { filter } from 'lodash/collection'

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/SearchForm.js
> +        <ul>
должно быть частью списка

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/elements/Like.js
> +import _ from 'lodash';
импортировать только используеме функции

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/elements/Pagination.js
> +  const menues = [];
map?

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/elements/SearchList.js
> +import _ from 'lodash';
импортировать конкретные функции

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/elements/SearchList.js
> +  const foundBlogsList = _.map(foundBlogs,
почему не отдельный компонент?

2017-02-01 10:12 UTC, index01d commented on src/components/widgets/blog/elements/TextBox.js
> +import { postsPath } from 'helpers/routes';
лучше сделать преобразование в контейнерном компоненте и сюда передавать уже готовую ссылку

2017-02-01 10:12 UTC, index01d commented on src/routes/Blog.js
> +  path: '/about',
лучше тоже обернуть в pathHelper

2017-02-01 10:13 UTC, index01d commented
Это не последние комментарии, но нужно сначала внести эти изменения и продолжим:)

2017-02-01 23:53 UTC, gnomePasaran commented
Спасибо за замечания. Я поменял то что понял, как поменять, для быстроты написания решил пока оставить JSX, я не его фанат, по этому поменяю потом на non-JSX.

Основная проблема: я не понял как выделить PaginationContainer и вынести в него всё необходимое, я не понял как наладить взаимодействие по клику на страницу пагинации, чтобы отображались нужные посты на  странице. Как следует это реализовать? 
сделать обработчик клика в BlogPage и передавать его в PaginationContainer? 
или рендерить BlogList из PaginationContainer, а не из BlogPage?

Можно этот вопрос поподробней развернуть, объяснить развёрнута, или дать ссылку на пример?

Заранее спасибо)

2017-02-01 23:54 UTC, gnomePasaran commented on src/components/BlogPage.js
>  class BlogPage extends React.Component {
Это я не смог сделать, в низу подруобно описал в чём моя проблема)

2017-02-02 12:25 UTC, gnomePasaran commented
У меня возник в голове ещё вопрос, по какому критерию мне чётко отделять презинтационные компоненты от контейнерных? 
в контейнерных не должно быть html/DOM - элементов, а только те которые я запилил сам?

2017-02-02 23:13 UTC, gnomePasaran commented on src/components/containers/BlogPage.js
> -    const postsOnThePage = 3;
я правильно понимаю, что нужно это вынести в контейнерный компонент PaginationContainer?
и правильно ли ядумаю, что логика этой функции, по хорошему, должна быть выполнена на сервере, а назад возвращены не весь масси постов, а лишь те что попадают на нужную страницу?

2017-02-03 05:54 UTC, index01d commented on src/components/containers/BlogPage.js
> -    const postsOnThePage = 3;
да, стоило бы выделить пейджинацию в отдельный компонент. По поводу того где должна быть пейджинация: обычно действительно данная логика обрабатывается сервером. Но в учебном приложении это непринципиально.

2017-02-04 08:09 UTC, index01d approved these changes
Я рекомендую именовать представления одинаково, то есть если ставить на конце View, то всем ставить, или никому не ставить.

Еще я рекомендую внутри директории контейнеров завести структуру похожую на структуру апки, тогда они не перемешаются и легко можно будет найти контейнер для интересующего компонента.

2017-02-04 08:09 UTC, index01d commented on src/components/containers/BlogPage.js
> +      'http://localhost:3001',
URL до сервера лучше вынести в constants

2017-02-04 08:09 UTC, index01d commented on src/routes/Blog.js
> +  path: postsAbout,
для унификации лучше, если это всегда будет функция

2017-02-04 08:09 UTC, index01d commented on .eslintrc.js
> +    "max-len": ["error", 120, 2],
хитроу

2017-02-04 21:11 UTC, gnomePasaran commented on .eslintrc.js
> +    "max-len": ["error", 120, 2],
))) да, маленький мухлёж, просто, было несколько моментов, что из-за переносов неулавливал очевиднейшие ошибки. получу `approve` верну всё к классике ;)

2017-02-04 21:33 UTC, gnomePasaran commented on src/components/containers/PaginationContainer.js
> +    this.props.paginationHandleClick(pageId);
Вот, не знаяю, это вообще законно так делать? Такой подход приемлем, и если да, то на сколько?

2017-02-04 21:44 UTC, gnomePasaran commented on src/components/containers/PaginationContainer.js
> +    this.props.paginationHandleClick(pageId);
Вот, не знаю, это вообще законно так делать? Такой подход приемлем, и если да, то на сколько?

2017-02-05 09:46 UTC, index01d commented
> сделать обработчик клика в BlogPage и передавать его в PaginationContainer?

Это решение нам подойдет, а так прув

2017-02-05 09:46 UTC, index01d approved these changes

2017-02-05 21:57 UTC, merged