Lesson 8
gnomePasaran/blog-platform-on-react pull request #8
Opened 2017-04-05 19:10 UTC by gnomePasaran

Привет, Эдуард. Наконец доделал урок, надеюсь получилось нормально. 
Я так и не получил фидбек по 7-му уроку, `https://github.com/gnomePasaran/blog-platform-on-react/pull/7`, я понимаю, что времени мало, что заднаний много, как и учеников. Так что забыть не сложно. С не термением жду ревью  :smile:

2017-04-06 07:39 UTC, index01d commented
Ого! Вот это прокол от меня был. Все review сегодня поступят.

2017-04-06 08:23 UTC, index01d requested changes
Первая порция правок и замечаний:) Сразу по все направлениям

2017-04-06 08:23 UTC, index01d commented on initializers/server/render.js
> +    Promise.all(compact(prepareData(store, renderProps))).then(() => {
здесь также стоит обработать ситуацию, когда какой-то из промисов провалился с 404 или 500 или еще чем-то. То есть допустим роут относится к записи блога, но такой записи сервер не вернул.

2017-04-06 08:23 UTC, index01d commented on src/components/layouts/MainLayout.js
> +    <Helmet>
теоретически лучше поднять еще на уровень выше, т.к. Layout'ов впоследствии может быть много

2017-04-06 08:23 UTC, index01d commented on src/components/views/Pagination.js
> +        <Menu.Item key={i} name={i.toString()} active={activePage === i} onClick={() => handlePageSelect(i)} />
в такой реализации, ссылки не будут индексироваться поисковиком (потому что они кнопки).

2017-04-06 08:23 UTC, index01d commented on src/components/views/widgets/BlogItem.js
> +import { postPath } from 'helpers/routes';
лучше обработать объект с записью в контейнере и сформировать готовый URL там, тогда презентационный компонент не будет знать о роутерной логике.

2017-04-06 08:23 UTC, index01d commented on src/components/views/widgets/BlogItem.js
> +    <Like blog={blog} handleLikeClick={handleLikeClick} />
опрятнее бы смотрелся комплект свойств id, count, onClick. Последнее просто выглядело бы более стандартно, а первые два с заделом на то, что компонент будет реиспользоваться с другими сущностями (лайк комментов, например).

2017-04-06 08:23 UTC, index01d commented on src/components/views/widgets/BlogItem.js
> +    <Like blog={blog} handleLikeClick={handleLikeClick} />
в целом по проекту лучше избегать передачи избыточных данных презентационным компонентам

2017-04-06 08:23 UTC, index01d commented on src/containers/PostContainer.js
> +export default connect(stateToProps, { handleLikeClick: createPostLike })(Post);
а это работает? ты тут передал actionCreator вместо диспетчеризации

2017-04-06 08:23 UTC, index01d commented on src/containers/PostsContainer.js
> +export default connect(stateToProps, { handleLikeClick: createPostLike })(Index);
и тут тоже

2017-04-06 08:23 UTC, index01d commented on src/reducers/Posts.js
> +    case 'CREATE_POST_LIKE_SUCCESS':
а чего константу пожалел?:)

2017-04-06 08:23 UTC, index01d commented on src/reducers/Posts.js
> +const updatedItems = (entries, response) => {
entries, { id, meta }

2017-04-06 08:23 UTC, index01d commented on src/reducers/Posts.js
> +  const { id, meta } = response;
тогда здесь не нужно будет деструктурировать

2017-04-06 08:23 UTC, index01d commented on src/reducers/Posts.js
> +      return assign({}, initialState, { entries: updatedItems(state.entries, action.response) });
а можно было для любителей mongoDB (см https://github.com/kolodny/immutability-helper):
```
const { id, meta } = action.reponse;

if (!isEmpty(state.entries))
  assign(
    {},
    initialState,
    { 
      entries: update(
        cloneDeep(state.entries), 
        { [findIndex(state.entries, { id })]: { meta: { $set: meta } } } }
      )
    }
  )
```

2017-04-06 08:23 UTC, index01d commented on src/reducers/Posts.js
> +      return assign({}, initialState, { entries: updatedItems(state.entries, action.response) });
в случае разрастания этого адища в production проектах можно смотреть в сторону immutable.js. Но это так, на будущее:)

2017-04-08 14:35 UTC, gnomePasaran commented on src/reducers/Posts.js
> +      return assign({}, initialState, { entries: updatedItems(state.entries, action.response) });
Cпасибо, прочёл, оценил, классная вещь!

2017-04-08 14:41 UTC, gnomePasaran commented on src/reducers/Posts.js
> +  const { id, meta } = response;
Линтер ругается на деструктурирование, когда больше чем 1 входной параметр. Но я поменял.)

2017-04-08 14:59 UTC, gnomePasaran commented
У меня есть некоторые вопросы.
1. Для отправки middleware'ом запроса с нужным параметром(`localhost:3000/?page=2`), насколько это приемлемо использовать для пагинации, реакт-роутер `history.push(path);`?
2. Было замечание про передачу функции, контейнеру а не отправку функции на деспетчеризацию `export default connect(stateToProps, { handleLikeClick: createPostLike })(Post);`, честно говоря этот код работает, но я переделал(как мне кажется верно). И работает как и прежде. я подсмотрел это решение здесь https://github.com/thrasherDGK/YABP/blob/master/src/containers/BlogList.jsx . Вопрос такой, если у меня есть функция, объявленная в контейнере и я хочу передать её дальше в контейнер-представление, я должен передавать её через `actinsToProps()` и отправлять на диспетчеризацию?

2017-04-08 16:46 UTC, index01d commented
> насколько это приемлемо использовать для пагинации, реакт-роутер 

C тем же успехом можно просто сформировать <Link>, в этом случае ссылка будет индексироваться поисковиком.

> если у меня есть функция, объявленная в контейнере и я хочу передать её дальше в контейнер-представление, я должен передавать её через actinsToProps() и отправлять на диспетчеризацию?

Можно всегда передавать ее через actionToProps, но диспетчеризировать, очевидно, нужно только action'ы, с обычными функциями этого делать не нужно

2017-04-08 16:52 UTC, index01d approved these changes
Подтверждаю задание. При желании можно еще сократить количество параметров для компонента Like при использовании в списке/внутренней странице и исключить дублирование функции в контейнере путем создания LikeContainer.

На местах соответственно вместо `<Like>` использовать `<LikeContainer>`, который будет получать просто id записи (`<LikeContainer id={item.id} />`) и уже в контейнере формировать выборку из состояния остальных свойств для Like (т.к. у нас есть в stateToProps(state, ownProps) доступ к свойствам, то ничего не мешает нам сделать соответствующую выборку из общего состояния).

2017-04-11 08:19 UTC, index01d commented
пора мержить?:)

2017-04-15 16:32 UTC, merged